import Head from 'next/head'
import Layout from '../components/layouts/Layout'
import Introduction from '../components/Home Page/Introduction'
import Technical from '../components/Technical'
import Projects from '../components/Home Page/Projects'
import HireMe from '../components/Home Page/HireMe'
import Reviews from '../components/Home Page/Reviews'
import TechInfoSlide from '../components/Home Page/TechInfoSlide'

import { useState,useEffect } from 'react'



// export async function getStaticProps(context) {
//   const res = await fetch(`http://portfoliobackend.local/wp-json/wp/v2/personal_portfolio`)
//   const data = await res.json()

//   if (!data) {
//     return {
//       notFound: true,
//     }
//   }

//   return {
//     props: { data }, // will be passed to the page component as props
//   }
// }


export async function getStaticProps(context) {
  

  const [data,tech] = await Promise.all([
      fetch(`http://portfoliobackend.local/wp-json/wp/v2/personal_portfolio`).then(r => r.json()),
      fetch(`http://portfoliobackend.local/wp-json/wp/v2/tech_skills/`).then(r => r.json())
    ]);
  

    return {
      props: {
              data:data,
              tech:tech,
              
      }
      }

};



// http://portfoliobackend.local/wp-json/wp/v2/tech_skills/



export default function Home({data,tech}) {
  let [showSlide, setShowSlide ] = useState(false)
  let [ slideImg, setSlideImg ] = useState(String)
  let [ slideText, setSlideText ] = useState(String)

  let [pageState, setPageState] = useState({
    
  })



  useEffect(() => {
    console.log(tech)
    const apiData = data[0].ACF

    

      setPageState:setPageState({
        introImg:apiData.about_me_image.url,
        introText:apiData.about_me,
        hireTitle:apiData.hire_title,
        hireText:apiData.hire_me,
        techExperience:{
        react:{
          experience:apiData.react_experience
        },
        swift:{
          experience:apiData.swift_experience
        },
        php:{
          experience:apiData.php_experience
        },
        sass:{
          experience:apiData.sass_experience
        },
        next:{
          experience:apiData.next_experience
        },
        vue:{
          experience:apiData.vue_experience
        },
        wordpress:{
          experience:apiData.wordpress_experience
        },
        nuxt:{
          experience:apiData.nuxt_experience
        }
      }
      })


  } ,[])

  



  function toggleSlide(bool:boolean,logo:string,text:string):void{
    console.log('The slide is working')
    setShowSlide(bool)
    setSlideImg(logo)
    setSlideText(text)

  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout>
      <Introduction image={pageState.introImg} text={pageState.introText}></Introduction>

      {
        showSlide ? <TechInfoSlide toggleSlide={toggleSlide} slideImg={slideImg} slideText={slideText}/> : <Technical techData={tech} toggleSlide={toggleSlide} />
      }
      
   
    <Projects></Projects>
   
     
    
     <Reviews></Reviews>
    

      
     
      <HireMe title={pageState.hireTitle} text={pageState.hireText}></HireMe>
     
     
    </Layout>
    </div>

      
   
  )
}


interface techExperience {
  obj:{
    react:{
     react:{
      experience:string
    },
    swift:{
      experience:string
    },
    php:{
      experience:string
    },
    sass:{
      experience:string
    },
    next:{
      experience:string
    },
    vue:{
      experience:string
    },
    wordpress:{
      experience:string
    },
    nuxt:{
      experience:string
    }
    },
    swift:{
      experience:string
    },
    php:{
      experience:string
    },
    sass:{
      experience:string
    },
    next:{
      experience:string
    },
    vue:{
      experience:string
    },
    wordpress:{
      experience:string
    },
    nuxt:{
      experience:string
    }
  }
}

interface setPageState {
  obj:{
    introImg:string,
    introText:string
    hireTitle:string,
    hireText:string,
    techExperience:techExperience
  }
  // Add more typesafty later
  
}