import Head from 'next/head'
import Layout from '../components/Layout'
import Introduction from '../components/Introduction'
import Technical from '../components/Technical'
import Projects from '../components/Projects'
import HireMe from '../components/HireMe'
import Reviews from '../components/Reviews'
import TechInfoSlide from '../components/TechInfoSlide'
import { useState } from 'react'

export default function Home() {
  let [showSlide, setShowSlide ] = useState(false)
  let [ slideImg, setSlideImg ] = useState(String)
  let [ slideText, setSlideText ] = useState(String)

  function toggleSlide(bool,logo,text){
    console.log('The slide is working')
    setShowSlide(bool)
    setSlideImg(logo)
    setSlideText(text)

  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout>
      <Introduction></Introduction>

      {
        showSlide ? <TechInfoSlide toggleSlide={toggleSlide} slideImg={slideImg} slideText={slideText}/> : <Technical toggleSlide={toggleSlide} />
      }
      
    <section>
    <Projects></Projects>
    </section>
     
     <section>
     <Reviews></Reviews>
     </section>

      
      <section>
      <HireMe></HireMe>
      </section>
     
    </Layout>
      

      
    </div>
  )
}
