import Head from 'next/head'
import Layout from '../components/layouts/Layout'
import Introduction from '../components/Home Page/Introduction'
import Technical from '../components/Technical'
import Projects from '../components/Home Page/Projects'
import HireMe from '../components/Home Page/HireMe'
import TechInfoSlide from '../components/Home Page/TechInfoSlide'
import Testimonial from '../components/Carousels/Testimonial'


import { useState,useEffect } from 'react'





export async function getStaticProps(context) {

  const [data,tech,testimonialData,portfolioItems] = await Promise.all([
      fetch(process.env.NEXT_PUBLIC_PERSONAL_PORTFOLIO_API
      ).then(r => r.json()),
      fetch(process.env.NEXT_PUBLIC_TECH_SKILLS_API).then(r => r.json()),
      fetch(process.env.NEXT_PUBLIC_TESTIMONIAL_API).then(r => r.json()),
      fetch(process.env.NEXT_PUBLIC_ITEM_API).then(r => r.json())


    ]);

    
  
    if (!data) {
      return {
        notFound: true,
      }
    }

    return {
      props: {
              data,
              tech,
              testimonialData,
              portfolioItems
              
      }
      }

};





export default function Home({data,tech,testimonialData,portfolioItems}) {

  let [showSlide, setShowSlide ] = useState(false)
  let [ slideImg, setSlideImg ] = useState(String)
  let [ slideTitle, setSlideTitle ] = useState(String)
  let [ slideContent, setSlideContent ] = useState(String)

  let [pageState, setPageState] = useState(Object)

 

  useEffect(() => {
    const apiData = data[0].ACF


      setPageState:setPageState({
        introImg:apiData.about_me_image.sizes.medium,
        introtitle:apiData.about_me,
        hireContent:apiData.hire_me
      })
      
       
  } ,[])

  



  function toggleSlide(bool:boolean,logo:string,title:string,content:string):void{
    setShowSlide(bool)
    setSlideImg(logo)
    setSlideTitle(title)
    setSlideContent(content)

  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />


      </Head>
    <Layout>
    
    

      <Introduction image={pageState.introImg} text={pageState.introtitle}></Introduction>

      {
        showSlide ? <TechInfoSlide toggleSlide={toggleSlide} slideImg={slideImg} slideTitle={slideTitle} slideContent={slideContent}/> : <Technical techData={tech} toggleSlide={toggleSlide} />
      }
      
   
    <Projects recentProject={portfolioItems}></Projects>
   
     
    
     <Testimonial data={testimonialData}/>
    
     
      
     
      <HireMe  text={pageState.hireContent}></HireMe>
     
     
    </Layout>
    </div>

      
   
  )
}


interface techExperience {
  obj:{
    react:{
     react:{
      experience:string
    },
    swift:{
      experience:string
    },
    php:{
      experience:string
    },
    sass:{
      experience:string
    },
    next:{
      experience:string
    },
    vue:{
      experience:string
    },
    wordpress:{
      experience:string
    },
    nuxt:{
      experience:string
    }
    },
    swift:{
      experience:string
    },
    php:{
      experience:string
    },
    sass:{
      experience:string
    },
    next:{
      experience:string
    },
    vue:{
      experience:string
    },
    wordpress:{
      experience:string
    },
    nuxt:{
      experience:string
    }
  }
}

interface setPageState {
  obj:{
    introImg:string,
    introtitle:string
    hireContent:string,
    hireContent:string,
    techExperience:techExperience
  }
  // Add more typesafty later
  
}